CREATE DATABASE COMPUTER_VISION
USE COMPUTER_VISION
CREATE TABLE FACEDATA(
    PERSON_NAME VARCHAR(100) NOT NULL,
    FEATURE VARCHAR(MAX) UNIQUE NOT NULL)
DROP TABLE FACEDATA
TRUNCATE TABLE FACEDATA
SELECT PERSON_NAME,COUNT(FEATURE) AS QTY
FROM FACEDATA
GROUP BY PERSON_NAME
ORDER BY PERSON_NAME ASC
SELECT * FROM FACEDATA